name: rotated_corner_decoration
description: RotatedCornerDecoration package was developed to create and apply corner badges. It provides auto rotation of TextSpans.
version: 2.1.0
homepage: https://github.com/kalaganov/corner_decoration

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
